config/routes.rb
TransitRails::Application.routes.draw do
  resources :users
  resources :lines
  resources :stations
  resources :sessions, only: [:new, :create, :destroy]
  resources :user_stations, only: [:create, :destroy]

  match '/signup',  to: 'users#new'
  match '/login',   to: 'sessions#new'
  match '/profile', to: 'users#show'
  match '/logout',  to: 'sessions#destroy'

  match '/removestation', to: 'user_stations#destroy'
  match '/addstation', to: 'user_stations#create', :via => :post

  root :to => 'lines#index'
end

app/models/connection.rb
class Connection < ActiveRecord::Base
	attr_accessible :station_id, :line_id, :sort_id

  belongs_to :station
  belongs_to :line

  validates_uniqueness_of :station_id, :scope => :line_id
end

app/models/line.rb
class Line < ActiveRecord::Base
	attr_accessible :name, :color

  has_many :connections, :dependent => :destroy
  has_many :stations, :through => :connections  
  has_many :user_lines, :dependent => :destroy
  has_many :users, :through => :user_lines

  validates_presence_of :name, :color
  validates_uniqueness_of :name, :color

  def to_param
  	name.downcase
	end
end

app/models/station.rb
class Station < ActiveRecord::Base
	attr_accessible :name, :cta_id, :latitude, :longitude

  has_many :stops, :dependent => :destroy
  has_many :connections, :dependent => :destroy
  has_many :lines, :through => :connections
  has_many :user_stations, :dependent => :destroy
  has_many :users, :through => :user_stations

  validates_presence_of :name, :cta_id
  validates_uniqueness_of :cta_id
  validates_uniqueness_of :latitude, :scope => :longitude

  def to_param
  	cta_id
	end
end

app/models/stop.rb
class Stop < ActiveRecord::Base
	attr_accessible :cta_id, :station_id, :direction

	belongs_to :station

	validates_presence_of :cta_id, :direction
	validates_uniqueness_of :cta_id
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :email, :password
  
  has_many :user_stations, :dependent => :destroy
  has_many :stations, :through => :user_stations
  has_many :user_lines, :dependent => :destroy
  has_many :lines, :through => :user_lines

  has_secure_password

  validates_uniqueness_of :username, :email
  validates_presence_of :username, :email, :password
  validates_format_of :email, with: /\b[A-Z0-9._%-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b/i
  validates_length_of :password, minimum: 4
end

app/models/user_line.rb
class UserLine < ActiveRecord::Base
	attr_accessible :user_id, :line_id

  belongs_to :user
  belongs_to :line

  validates_uniqueness_of :user_id, :scope => :line_id
end

app/models/user_station.rb
class UserStation < ActiveRecord::Base
	attr_accessible :user_id, :station_id

  belongs_to :user
  belongs_to :station

  validates_uniqueness_of :user_id, :scope => :station_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include ApplicationHelper
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  def index
    @lines = Line.all
  end
  
  def show
    @line = Line.find_by_name(params[:id].capitalize)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController  
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_username(params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/profile'
    else
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  def show
    @station = Station.find_by_cta_id(params[:id])
    @line_count = @station.lines.count
  end
end

app/controllers/user_stations_controller.rb
class UserStationsController < ApplicationController
  def create
  	@station = Station.find_by_id(params[:station_id])
  	current_user.stations << @station
  	redirect_to station_path(@station)
  end

  def destroy
    current_user.user_stations.find_by_station_id(params[:station_id]).destroy
    redirect_to '/profile'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    redirect_to '/profile' if current_user
    @user = User.new
  end

  def create
    user = User.new(params[:user])
    if user.save
      session[:user_id] = user.id
      redirect_to '/profile'
    else
      render :new
    end
  end

  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	include SessionsHelper
	include TrainsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/helpers/trains_helper.rb
module TrainsHelper
	def time(input, sched)
		estimate = ((Time.parse(input) - Time.now)/60).to_i + 1
		
		if estimate > 1
			output = "#{estimate.to_s}m"
		else
			output = "Due"
		end

		if sched == "1"
			output + "*"
		else
			output
		end
	end

	def sort_arrivals(input)
		input.sort_by { |k| k["arrT"] }
	end
end

app/views/layouts/_nav.html.erb
<!-- <div id="nav-accent">
  <div class="nav-accent-color" id="red"></div>
  <div class="nav-accent-color" id="blue"></div>
  <div class="nav-accent-color" id="brown"></div>
  <div class="nav-accent-color" id="green"></div>
  <div class="nav-accent-color" id="orange"></div>
  <div class="nav-accent-color" id="purple"></div>
  <div class="nav-accent-color" id="pink"></div>
  <div class="nav-accent-color" id="yellow"></div>
</div> -->
<nav>
  <div id="title">
    <%= link_to "Chicago Train Tracker", root_url %>
  </div>
  <div id="nav-links">
    <% unless current_user %>

      <div><%= link_to "Signup", '/signup' %></div>
      <div><%= link_to "Login", '/login' %></div>
    <% end %>
    <% if current_user %>
      <div><%= link_to "Profile", '/profile' %></div>
      <div><%= link_to "Logout", logout_path %></div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TransitRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=" + ENV["GOOGLE_MAPS_KEY"] + "&sensor=false" %>
	<%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= csrf_meta_tag %>
</head>
<body>
  <%= render partial: 'layouts/nav' %>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/lines/_listview.html.erb
<div class="line-parent" id="<%= line.name.downcase %>">
	<%= link_to line_path(line) do %>
    <div class="line-child">
    	<%= line.name %>
    </div>
  <% end %>
</div>

app/views/lines/_vertical_map.html.erb
<div class="vertical-map" style="background-color: <%= line.color %>; height: <%= line.stations.count * 37.9 %>px">
  <% line.stations.count.times do %>
		<div class="vertical-map-dot"></div>
	<% end %>
</div>

app/views/lines/index.html.erb
<div id="line-list-container">
  <% @lines.each do |line| %>
		<%= render partial: 'lines/listview', locals: {line: line} %>
  <% end %>
</div>

app/views/lines/show.html.erb
<div class="line-header" id="<%= @line.name.downcase %>">
  <h2><%= @line.name %></h2>
</div>

<%= render partial: 'lines/vertical_map', locals: {line: @line} %>

<% @line.stations.order("sort_id").each do |station| %>
  <%= render partial: 'stations/listview', locals: {station: station} %>
<% end %>

app/views/stations/_data.html.erb
<div class="data-container">
	<% directions = [] %>
	<% @station.stops.each {|stop| directions << stop.direction if !directions.include?(stop.direction)} %>
	<% directions.sort.each do |direction| %>
		<% trains = [] %>
		<% @station.stops.each do |stop| %>
			<% if stop.direction == direction %>
				<% trains_data = CTA::TrainTracker.arrivals :stpid => stop.cta_id %>
				<% trains_data.each {|train| trains << train} %>
			<% end %>
		<% end %>
		<div class="stop">
			<h2><%= direction %></h2>
			<% sort_arrivals(trains).each do |train| %>
				<% unless train.destNm == @station.name %>
					<div class="train" id="<%= train.rt.downcase %>">
						<div class="train-dest"><%= train.destNm %></div>
						<div class="train-time"><%= time(train.arrT, train.isSch) %></div>
					</div>
				<% end %>
			<% end %>
		</div>
	<% end %>
	<h4>* scheduled</h4>
</div>

app/views/stations/_header.html.erb
<div class="station-header">
	<div class="sh-left">
		<% @station.lines.each do |line| %>
		<div class="station-color" style="height: <%= (1.0 / @station.lines.count * 100).to_s %>%; background-color: <%= line.color %>">
		</div>
		<% end %>
		<% case @line_count %>
		<% when 2 %>
			<div class="station-color-divider"></div>
		<% when 3 %>
			<div class="station-color-divider" style="top: -49px; height: 3px"></div>
			<div class="station-color-divider" style="top: -28px; height: 3px"></div>
		<% end %>
	</div>
	<div class="sh-center"><h2><%= @station.name %></div>
	<div class="sh-right">
		<% @station.lines.each do |line| %>
		<div class="station-color" style="height: <%= (1.0 / @station.lines.count * 100).to_s %>%; background-color: <%= line.color %>">
		</div>
		<% end %>
		<% case @line_count %>
		<% when 2 %>
			<div class="station-color-divider"></div>
		<% when 3 %>
			<div class="station-color-divider" style="top: -49px; height: 3px"></div>
			<div class="station-color-divider" style="top: -28px; height: 3px"></div>
		<% end %>
	</div>
</div>

app/views/stations/_listview.html.erb
<div>
 <div class="station-name">
	<%= link_to station.name, station_path(station) %>
 </div>

  <% station.lines.each do |line| %>
    <% if line.name != @line.name %>
    <div class="line-icon" id="<%= line.name.downcase %>">&nbsp;</div>
    <% end %>
  <% end %>
</div>

app/views/stations/show.html.erb
<%= render partial: 'stations/header', locals: {station: @station} %>

<form id="add-station-form" action="/addstation" method="post">
	<input type="hidden" name="station_id" value="<%= @station.id %>">
	<input type="submit" value="Add Station">
</form>

<%= render partial: 'stations/data', locals: {station: @station} %>

<div id="map-canvas"></div>
<input type=hidden id="latitude" value="<%= @station.latitude %>">
<input type=hidden id="longitude" value="<%= @station.longitude %>">

app/views/users/new.html.erb
<h1>Signup</h1>

<%= form_for @user do |f| %>
  <%= f.text_field :username, placeholder: "Username" %><br>
  <%= f.email_field :email, placeholder: "Email" %><br>
  <%= f.password_field :password, placeholder: "Password" %><br>
  <%= f.submit "Signup" %>
<% end %>

app/views/users/show.html.erb
<h2>My Stations</h2>

<% current_user.stations.each do |station| %>
  <div>
   <div class="station-name">
		<%= link_to station.name, station_path(station) %>
   </div>
    <% station.lines.each do |line| %>
      <div class="line-icon" id="<%= line.name.downcase %>">&nbsp;</div>
    <% end %>
    <div class="delete-station-x">
    	<%= link_to "x", removestation_path(:station_id => station.id) %>
    </div>
  </div>
<% end %>